import React from 'react';
// new comment
const About = props => {
  return (
    <div>
      <div className="profiles" ><img className="pics" src="https://avatars0.githubusercontent.com/u/48890327?s=400&v=4" alt="Kishor"/><section> <h3> Kishor Pandey </h3> <p>I am a Software Development Apprentice at AWS, Directory Services team. My most recent experience has been handling petroleum at US Army. In the Army, I supported an organization of 500 employee, about 300 motor vehicles and equipment with petroleum products.<br /><br />One reason I particularly am enjoy coding is the challenges we face to build awesome applications. Being a new field, feels like even more challenging. I graduated from Metropolitan State University, Saint Paul MN majoring in Management Information Systems.<br /><br /> Here at Code Fellows, I feel I am learning a lot to become a successful at programming. I like playing ping-pong in my free time. I was born and raised in Pokhara, Nepal which is also a rainy city like Seattle.</p></section></div>
      
      <div className="profiles" ><img className="pics" src="https://avatars2.githubusercontent.com/u/48736239?s=400&v=4" alt="Peter" /> <section><h3> Peter Tynan </h3> <p>I love to launch myself out of my bubble. The two greatest traits I value in a person are critical thinking and empathy. I'm getting a tattoo of the word 'indecisive', but I'm not sure where to put it. <br/><br/> I'm new to the field of programming, and hungry to learn more. In a past life I was going to be a math teacher, and those experiences teaching have allowed me to sharpen myself as a learner. I spent 7 months last year training with the US Army, eating dirt and learning the secrets of network administration. Now I am learning Software Development and looking forward to adding even more tools to my belt! <br/><br/> I give a mean explanation of the Monty Hall problem. Born and raised in the PNW - naturally I love the rain. Experienced with customer service and with a mop. My passions include stories, games, puzzles, and horrible puns.</p></section></div>

      
      <div className="profiles" ><img className="pics" src="https://avatars2.githubusercontent.com/u/44951141?s=400&v=4" alt="Cristian" /><section><h3> Cristian Restrepo </h3> <p>Coming from a background in finance, I am very excited about the opportunities that await me as software developer. <br/><br/> I knew that I wanted to become a software developer when, in my senior year of college, I took a class that made me build a profile on a website using HTML and CSS. Since graduation, I would teach myself how to develop in the spare time that I had. <br/><br/> Almost three years after graduating from college, I now have the opportunity to learn and grow with some amazing people in this Apprenti cohort and at Amazon. I am currently a Software Development Engineer Apprentice at Amazon Web Services.
      </p></section></div>
      <div className="profiles" ><img className="pics" src="https://avatars3.githubusercontent.com/u/43525370?s=400&v=4" alt="Xia" /><section><h3> Xia Liu </h3> <p>MS Information Systems and Operations management graduate with strong education background in information technology and management; diverse range of experience in IT-related positions; innovative at problem solving; excellent logical thinking and quantitative analytical abilities; creative and strategic leader with experience in a variety of different areas; results-oriented, well organized and detail oriented.<br /><br /> My career goal is to be a both generalist and specialist in integrated information technology field.</p></section></div>

      <div className="profiles" ><img className="pics" src="https://avatars3.githubusercontent.com/u/2334903?s=400&v=4" alt="Tisha" /><section> <h3> Tisha M Greenidge </h3> <p>My background experience includes Education, Project Management, Data Analytics and Web Development and Electrical (in the Navy Reserves). I started coding in high school, and wrote my first program in Quick Basic. Since then, I have written programs in C++, Pascal, Javascript, Ruby, Python and Java.<br /><br /> I am excited to be surrounded by incredibly smart people at Amazon, and hope to hone my software engineering skills that will allow me to develop software at scale.</p></section></div>
    </div>
    
  );
};

export default About;
