import React from 'react';

const About = props => {
  return (
    <div>
      <div className="profiles" ><img className="pics" src="https://avatars0.githubusercontent.com/u/48890327?s=400&v=4" alt="Kishor"/><section> <h3> Kishor Pandey </h3> <p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></section></div>
      
      <div className="profiles" ><img className="pics" src="https://avatars2.githubusercontent.com/u/48736239?s=400&v=4" alt="Peter" /> <section><h3> Peter Tynan </h3> <p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></section></div>
      <div className="profiles" ><img className="pics" src="https://avatars2.githubusercontent.com/u/44951141?s=400&v=4" alt="Christian" /><section><h3> Cristian Restrepo </h3> <p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></section></div>
      <div className="profiles" ><img className="pics" src="https://avatars3.githubusercontent.com/u/43525370?s=400&v=4" alt="Xia" /><section><h3> Xia Liu </h3> <p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></section></div>
      <div className="profiles" ><img className="pics" src="https://avatars3.githubusercontent.com/u/2334903?s=400&v=4" alt="Tisha" /><section> <h3> Tisha M Greenidge </h3> <p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></section></div>
    </div>
    
  );
};

export default About;
