import React from 'react';
import { Link } from 'react-router-dom';

const About = props => {
  return (
    <div>
      <div><img src="https://avatars0.githubusercontent.com/u/48890327?s=400&v=4" alt="Kishor"/><br />Kishor Pandey<p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></div>
      
      <div><img src="https://avatars2.githubusercontent.com/u/48736239?s=400&v=4" alt="Peter" /><br />Peter Tynan<p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></div>
      <div><img src="https://avatars2.githubusercontent.com/u/44951141?s=400&v=4" alt="Christian" /><br />Cristian Restrepo<p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></div>
      <div><img src="https://avatars3.githubusercontent.com/u/43525370?s=400&v=4" alt="Xia" /><br />Xia Liu<p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></div>
      <div><img src="https://avatars3.githubusercontent.com/u/2334903?s=400&v=4" alt="Tisha" /><br />Tisha M Greenidge<p>Lorem ipsum dolor sit amet, sit ante magna suspendisse maecenas, sit velit non per nulla quis pede, quam sed, et vivamus non id. Facilisis mauris amet, aliquam gravida id dapibus posuere et arcu, facilisis eget mattis nullam mauris praesent sed. Pede in cras amet elementum tristique pharetra. Et dictum donec hac erat, in corrupti ac, imperdiet cursus vel ac curae sem vestibulum, nibh pellentesque pharetra. At volutpat viverra euismod velit quod integer, turpis tellus proin placerat in eu. Sollicitudin ante iaculis dui ut sapien, doloribus magnis risus, suspendisse donec, sociis eros diam sollicitudin neque magna. Lacus ornare in in, vitae consequat a elementum magna, in consectetuer pede id orci, ridiculus magna.</p></div>
    </div>
    
  );
};

export default About;
